export default function Home() {
  return (
    <div className="px-24">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat. Pulvinar etiam non quam lacus. Enim nec dui nunc mattis. Potenti nullam ac tortor vitae purus faucibus. In cursus turpis massa tincidunt dui ut ornare. Mauris commodo quis imperdiet massa tincidunt nunc. Est placerat in egestas erat imperdiet sed euismod. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Vitae nunc sed velit dignissim sodales ut eu sem integer. Velit egestas dui id ornare arcu odio ut sem nulla. Ornare aenean euismod elementum nisi. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Ac feugiat sed lectus vestibulum mattis ullamcorper. Diam quam nulla porttitor massa id neque aliquam.

      Aliquet nibh praesent tristique magna sit amet purus. Massa placerat duis ultricies lacus. Eget est lorem ipsum dolor sit amet consectetur adipiscing. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Nulla aliquet enim tortor at auctor urna. A diam sollicitudin tempor id eu nisl nunc mi ipsum. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Urna id volutpat lacus laoreet non. Neque laoreet suspendisse interdum consectetur libero id. Fermentum leo vel orci porta non pulvinar neque laoreet. Nisi lacus sed viverra tellus in hac. Porta nibh venenatis cras sed. Est ultricies integer quis auctor. Consequat semper viverra nam libero justo laoreet sit amet cursus. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Duis at tellus at urna condimentum. Vulputate odio ut enim blandit volutpat maecenas. Elit at imperdiet dui accumsan sit.

      Lacus vestibulum sed arcu non. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Molestie a iaculis at erat pellentesque adipiscing. Orci nulla pellentesque dignissim enim sit amet venenatis. Ultrices sagittis orci a scelerisque purus semper eget duis at. Risus in hendrerit gravida rutrum quisque non tellus orci. Urna nec tincidunt praesent semper feugiat nibh sed. Elementum nibh tellus molestie nunc non blandit. Congue eu consequat ac felis donec. Sed turpis tincidunt id aliquet. Laoreet sit amet cursus sit amet. Urna neque viverra justo nec. Condimentum vitae sapien pellentesque habitant morbi tristique senectus.

      Arcu non odio euismod lacinia. Amet nulla facilisi morbi tempus iaculis urna. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Diam volutpat commodo sed egestas egestas. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Arcu ac tortor dignissim convallis aenean et. Amet est placerat in egestas erat imperdiet sed. In vitae turpis massa sed elementum. Eget magna fermentum iaculis eu non diam. Commodo nulla facilisi nullam vehicula ipsum a arcu. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Vel quam elementum pulvinar etiam non quam lacus suspendisse. Diam sollicitudin tempor id eu. Blandit volutpat maecenas volutpat blandit. Odio eu feugiat pretium nibh ipsum consequat nisl vel.

      Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Consectetur adipiscing elit pellentesque habitant morbi. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. A diam maecenas sed enim ut sem viverra. Nibh tellus molestie nunc non. Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Dui accumsan sit amet nulla facilisi. Leo in vitae turpis massa sed elementum tempus egestas sed. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Cras ornare arcu dui vivamus arcu felis bibendum ut. Mi quis hendrerit dolor magna eget est.

      At risus viverra adipiscing at in tellus. Nec dui nunc mattis enim ut tellus. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Amet nisl purus in mollis nunc sed id semper risus. Pulvinar mattis nunc sed blandit. Tristique et egestas quis ipsum. Nec dui nunc mattis enim ut tellus elementum. Feugiat sed lectus vestibulum mattis ullamcorper. Mauris a diam maecenas sed enim. Diam sit amet nisl suscipit adipiscing bibendum est. Morbi tristique senectus et netus et. Elementum integer enim neque volutpat ac tincidunt vitae semper. Lacus sed viverra tellus in. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Posuere sollicitudin aliquam ultrices sagittis orci. Felis bibendum ut tristique et egestas quis. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat.

      Purus semper eget duis at. Blandit volutpat maecenas volutpat blandit aliquam etiam. Enim sit amet venenatis urna cursus eget nunc. Sit amet consectetur adipiscing elit. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Ultrices tincidunt arcu non sodales neque. Nunc eget lorem dolor sed. Pellentesque elit ullamcorper dignissim cras tincidunt. Dolor magna eget est lorem ipsum. Feugiat in fermentum posuere urna. Neque egestas congue quisque egestas diam in arcu cursus euismod. In massa tempor nec feugiat. Eget duis at tellus at urna condimentum. Neque laoreet suspendisse interdum consectetur libero. Vehicula ipsum a arcu cursus vitae congue.

      Eget mi proin sed libero enim. Massa sed elementum tempus egestas sed sed. Lacinia at quis risus sed vulputate odio ut enim blandit. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Turpis egestas integer eget aliquet. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem. Adipiscing elit duis tristique sollicitudin nibh sit. At erat pellentesque adipiscing commodo elit at imperdiet. Aliquam etiam erat velit scelerisque in dictum non. Vulputate dignissim suspendisse in est ante in nibh. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Rhoncus dolor purus non enim praesent elementum.

      In hac habitasse platea dictumst quisque sagittis purus sit amet. Aliquam sem fringilla ut morbi tincidunt. Lobortis scelerisque fermentum dui faucibus in ornare. Tristique senectus et netus et malesuada. Malesuada fames ac turpis egestas maecenas pharetra. Arcu cursus euismod quis viverra. Cras adipiscing enim eu turpis egestas pretium aenean. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Varius duis at consectetur lorem donec massa sapien faucibus. Praesent tristique magna sit amet purus. Semper auctor neque vitae tempus.

      Pharetra magna ac placerat vestibulum lectus mauris. Accumsan lacus vel facilisis volutpat est velit egestas dui id. In vitae turpis massa sed elementum tempus egestas. Netus et malesuada fames ac turpis. Pharetra magna ac placerat vestibulum. Vitae semper quis lectus nulla at. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Arcu ac tortor dignissim convallis aenean et tortor. Commodo elit at imperdiet dui accumsan sit. Sed id semper risus in. Leo urna molestie at elementum.    </div>
  )
}

// TODO
// Form to add blog
// Look for blog [id]
// Search for blog
// Translation